spring:
  application:
    name: server-registry

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    enabled: false
